# Business Analyst/Data Scientist {-}

## Who exactly is a Data person? {-}

> You have data. To use this data to inform your decision-making, it needs to be relevant, well-organized, and preferably digital. Once your data is coherent, you proceed with analyzing it and creating dashboards and reports to understand your business’s performance better. Then you set your sights on the future and start generating predictive analytics. With predictive analytics, you assess potential future scenarios and predict consumer behavior in creative ways.


## What do they do? {-}

* Find patterns and trends in datasets to uncover insights
* Create algorithms and data models to forecast outcomes
* Use machine learning techniques to improve the quality of data or product offerings
* Communicate recommendations to other teams and senior staff
* Deploy data tools such as Python, R, SAS, or SQL in data analysis
* Stay on top of innovations in the data science field

## Business analyst vs data scientist: What’s the difference? {-}

> The work of Business analysts and data scientists can seem similar—both find trends or patterns in data to reveal new ways for organizations to make better decisions about operations. But data scientists tend to have more responsibility and are generally considered more senior than data analysts.\
Data scientists are often expected to form their own questions about the data, while data analysts might support teams that already have set goals in mind. A data scientist might also spend more time developing models, using machine learning, or incorporating advanced programming to find and analyze data.\
Many data scientists can begin their careers as analysts or statisticians


## Skills required for these roles {-}

### Programming languages: {-} 
Data scientists can expect to spend time using programming languages to sort through, analyze, and otherwise manage large chunks of data. Popular programming languages for data science include: Python, R, SQL,SAS

### Data visualization: {-}
Being able to create charts and graphs is a significant part of being a data scientist. Familiarity with the following tools should prepare you to do the work:
Tableau, PowerBI, Excel

### Machine learning: {-} 
Incorporating machine learning and deep learning into your work as a data scientist means continuously improving the quality of the data you gather and potentially being able to predict the outcomes of future datasets. A course in machine learning can get you started with the basics.

### Big data: {-} 
Some employers may want to see that you have some familiarity grappling with big data. Some of the software frameworks used to process big data include Hadoop and Apache Spark.

### Communication: {-}
The most brilliant data scientists won’t be able to affect any change if they aren’t able to communicate their findings well. The ability to share ideas and results verbally and in written language is an often-sought skill in data scientists.

## Salary with years of experience: {-}

* Data Scientist Level 1  - $85,000–$110,000 (0-3 years of experience)			
* Data Scientist Level 2	- $120,000–$140,000 (4-8 years of experience)			
*  Data Scientist Level 3	- $148,000–$185,000 (9+ years of experience)			
* Data Scientist Manager Level 1	-  $132,000–$164,000 (supervises 1-3 people)			
* Data Scientist Manager Level 2	-  $180,000–$210,000 (supervises 4-9 people)			
* Data Scientist Manager Level 3	-  $210,000–$275,000 (supervises 10+ people)

## Admission timeline for these roles {-}

## Components of a Data Science interview porcess {-}

### Coding (38%) {-}

This will test your problem-solving skills and how you manipulate data using algorithms, SQL, etc. 
 
The coding aspect of a Data Science Interview takes the highest percentage, at 38%. More than a third of your interview will be based on coding, which is normal as you’re interviewing for a Data Science position. 

Coding questions aim to analyse and evaluate a candidate's proficiency with computer science and its fundamentals. It can cover the following topics:

Data Structures: Arrays, Dictionary, Stack/Queues, Strings, Tree/Binary Tree, and more.
Algorithms: Binary Search, Recursion, Sorting, and more.
SQL: Constraints, Primary/Foreign Key, Join, and more
 

### Statistics (21%) {-}

This will test your understanding of statistics as a whole and how you have and can apply them within problem-solving tasks.
 
Statistics is an important element of Data Science. Statistics help Data Scientists analyse large and complex datasets. It is heavily used for Machine Learning in improving models. 

Understanding popular statistical terminology and how it can be implemented within Data Science tasks will help you thrive as a Data Scientist. It can cover the following topics:

Probability Distributions
Hypothesis Testing
Modeling

 
### Machine learning (17%) {-}

This will test your ability to understand the theory behind Machine Learning, how to build models, how it applies to a specific problem/task at hand, and how you can improve it. 
 
With the use of Machine Learning models in our day-to-day lives, it becomes an important aspect of Data Science and how we can continuously improve it to be implemented into businesses and more. 

Data Scientists are known for solving problems and creating models, therefore during a Data Science interview, the interviewer will test your ability to build models, the overall workflow, and how to improve it. 

It can cover the following topics:

Artificial Intelligence
Model building, validations, and interpretations
Types of Algorithms
Use cases of Machine Learning
Example questions would be:

###  Business Case problems (12%) {-}
This will test your understanding of technical knowledge and how it can be used to drive business and determine the right decision to make. 
 
The reason that data is so valuable is that it can give people a greater understanding of the data and it can help make important decisions. 

Applying technical knowledge to business case scenarios will help the interviewer understand how you can improve and help grow the company using your skills. 

It can cover the following topics:

Performance and limitations of a product
Business short-term and long-term goals
Example questions would be:


### Behavioral questions (13%) {-}

This will test your characteristics and determine if you are a good fit for the company. 
 
Although the majority of technical jobs require heavy hard skills, soft skills are just as important. Your soft skills will determine if you are the right fit for the role. 

During the behavioral stage, articulating yourself using elements of your resume to back your point will make you successful. 

For example, some companies may prefer a candidate who is highly independent and requires little to no interaction. The interviewer will scan through your resume and ask how you had worked in your previous companies and your preferred working method. You will have an understanding that they require an independent employee and can draw out past experiences where you were independent.


### Important links

Resource for finding the most important topics for data science interviews -

*https://www.stratascratch.com/blog/314-resources-for-data-science-fundamentals/
*https://towardsdatascience.com/the-ultimate-interview-prep-guide-for-your-next-dream-data-job-be4b2c7f73a8
*https://www.simplilearn.com/tutorials/data-science-tutorial/data-science-interview-questions
*https://brainstation.io/career-guides/data-science-interview-questions


