# Business Analyst/Data Scientist {-}

## Who exactly is a Data person? {-}

> You have data. To use this data to inform your decision-making, it needs to be relevant, well-organized, and preferably digital. Once your data is coherent, you proceed with analyzing it and creating dashboards and reports to understand your business’s performance better. Then you set your sights on the future and start generating predictive analytics. With predictive analytics, you assess potential future scenarios and predict consumer behavior in creative ways.


## What does he do? {-}

* Find patterns and trends in datasets to uncover insights
* Create algorithms and data models to forecast outcomes
* Use machine learning techniques to improve the quality of data or product offerings
* Communicate recommendations to other teams and senior staff
* Deploy data tools such as Python, R, SAS, or SQL in data analysis
* Stay on top of innovations in the data science field

## Business analyst vs data scientist: What’s the difference? {-}

> The work of Business analysts and data scientists can seem similar—both find trends or patterns in data to reveal new ways for organizations to make better decisions about operations. But data scientists tend to have more responsibility and are generally considered more senior than data analysts.\
Data scientists are often expected to form their own questions about the data, while data analysts might support teams that already have set goals in mind. A data scientist might also spend more time developing models, using machine learning, or incorporating advanced programming to find and analyze data.\
Many data scientists can begin their careers as analysts or statisticians


## Skills required for these roles

### Programming languages: 
Data scientists can expect to spend time using programming languages to sort through, analyze, and otherwise manage large chunks of data. Popular programming languages for data science include: Python, R, SQL,SAS

### Data visualization: 
Being able to create charts and graphs is a significant part of being a data scientist. Familiarity with the following tools should prepare you to do the work:
Tableau, PowerBI, Excel

###Machine learning: 
Incorporating machine learning and deep learning into your work as a data scientist means continuously improving the quality of the data you gather and potentially being able to predict the outcomes of future datasets. A course in machine learning can get you started with the basics.

###Big data: 
Some employers may want to see that you have some familiarity grappling with big data. Some of the software frameworks used to process big data include Hadoop and Apache Spark.

### Communication: 
The most brilliant data scientists won’t be able to affect any change if they aren’t able to communicate their findings well. The ability to share ideas and results verbally and in written language is an often-sought skill in data scientists.

