# Product Manager {-}

## Who is a Product Manager? {-}

> A product manager connects business strategy, design knowledge, and customer needs in order to develop a product that is relevant, feasible, and valuable. PMs are focused on optimizing a product to achieve the business goals and user necessities while maximizing return on investment.

> They are the overseers of a company’s products and the technological innovation behind them, and the stewards of that innovation’s role in meeting the customers’ needs in the marketplace.



## What do they do? {-}

* Identify a problem - Product managers assess the market and suggest ways to leverage their company’s resources to create a product that will solve a problem for customers.

* Interview prospective customers - This enables product managers to get a feel for how the potential software or hardware product could be used and how much of a market exists for the product.

* Develop a proposal for the product - Product managers work closely with technologists to scope the technical parameters and determine what products and features will best align with the company’s business strategy. A great product that customers will love (and buy!) is said to have great product-market fit.

* Let the technical people build the tech - Product managers at this stage help things move along smoothly and check in to ensure the process stays on track.

* Ask thoughtful questions throughout. Keep the business strategy top of mind for the company. 

* Make sure the product works. Product managers constantly measure, test, and validate their product with their customers—to make sure that what the team has built meets customer needs as well as they had hoped. 

* Launch the product. Product managers work closely with the company’s marketing team to reach the right customers. 


## Skills required for these roles {-}

### Communication Skills: {-} 
> Product managers are the product champions and are responsible for guiding product ideas from start to finish.They should be able to communicate with different stakeholders (e.g., customers, product team members) in order to make sure they understand how their decisions will affect the product or business strategy. Communication skills help a product manager establish credibility, listen to their product team, and create a shared understanding of the product.

### Technical Expertise: {-}
> Product managers need to be able to understand product design, engineering, and coding.This means that they should know the difference between UX/UI designers, product engineers, and product developers and how each of their skills is fundamental in designing an outstanding product.Basic technical expertise is also important for understanding what problem a product solves and making sure the product is properly built and tested.

### Business Skills: {-} 
> Product managers must be able to use data-driven decision-making and understand the business side of product development.Product managers need these deep business skills because they have less time for traditional “product management” tasks like product planning or product design.The product manager role will evolve with product development to be more business-focused.

### Research Abilities: {-} 
> Product managers need product management skills and deep business knowledge, but they also must have a strong understanding of the customer.The product manager will then be able to apply their product development skills strategically with data-driven decision-making for an outstanding product that meets market needs in 2022. It is important for product managers to keep up with trends, product management techniques, and new product development strategies. Product managers should be able to understand the ever-changing customer needs, think strategically about diversifying or evolving products/services that already exist but are not meeting current market needs.

### Strategic Thinking Skills: {-}
> Product managers must be able to think about product strategy past what is simply on the product roadmap, and this means being able to anticipate possible hurdles or problems. This includes thinking of ways around a problem that have been tried before in order to come up with something new and innovative for their product.

### Prioritization Skills: {-}
> Product managers need to be able to prioritize product features, requirements, and tasks in order of importance. This means that product managers must know which product feature will have the most impact on their customers or potential customers.

## Salary with years of experience: {-}

* Associate product manager  - $80,000–$100,000 (0-3 years of experience)			
* Product manager	- $110,000–$140,000 (4-8 years of experience)			
* Senior product manager	- $135,000–$180,000 (9+ years of experience)			
* Director of product management	-  $150,000–$184,000 (supervises 3-5 PM)			
* VP of product management	-  $190,000–$230,000 (supervises 9-12 PM)			
* Chief product officer (CPO)	-  $210,000–$275,000 (supervises at company level)

## Admission timeline for these roles {-}

## Components of a Product Management interview porcess {-}

### Coding (38%)

This will test your problem-solving skills and how you manipulate data using algorithms, SQL, etc. 
 
The coding aspect of a Data Science Interview takes the highest percentage, at 38%. More than a third of your interview will be based on coding, which is normal as you’re interviewing for a Data Science position. 

Coding questions aim to analyse and evaluate a candidate's proficiency with computer science and its fundamentals. It can cover the following topics:

Data Structures: Arrays, Dictionary, Stack/Queues, Strings, Tree/Binary Tree, and more.
Algorithms: Binary Search, Recursion, Sorting, and more.
SQL: Constraints, Primary/Foreign Key, Join, and more
 

### Statistics (21%)

This will test your understanding of statistics as a whole and how you have and can apply them within problem-solving tasks.
 
Statistics is an important element of Data Science. Statistics help Data Scientists analyse large and complex datasets. It is heavily used for Machine Learning in improving models. 

Understanding popular statistical terminology and how it can be implemented within Data Science tasks will help you thrive as a Data Scientist. It can cover the following topics:

Probability Distributions
Hypothesis Testing
Modeling

 
### Machine learning (17%) 

This will test your ability to understand the theory behind Machine Learning, how to build models, how it applies to a specific problem/task at hand, and how you can improve it. 
 
With the use of Machine Learning models in our day-to-day lives, it becomes an important aspect of Data Science and how we can continuously improve it to be implemented into businesses and more. 

Data Scientists are known for solving problems and creating models, therefore during a Data Science interview, the interviewer will test your ability to build models, the overall workflow, and how to improve it. 

It can cover the following topics:

Artificial Intelligence
Model building, validations, and interpretations
Types of Algorithms
Use cases of Machine Learning
Example questions would be:

###  Business Case problems (12%) 
This will test your understanding of technical knowledge and how it can be used to drive business and determine the right decision to make. 
 
The reason that data is so valuable is that it can give people a greater understanding of the data and it can help make important decisions. 

Applying technical knowledge to business case scenarios will help the interviewer understand how you can improve and help grow the company using your skills. 

It can cover the following topics:

Performance and limitations of a product
Business short-term and long-term goals
Example questions would be:


### Behavioral questions (13%) 

This will test your characteristics and determine if you are a good fit for the company. 
 
Although the majority of technical jobs require heavy hard skills, soft skills are just as important. Your soft skills will determine if you are the right fit for the role. 

During the behavioral stage, articulating yourself using elements of your resume to back your point will make you successful. 

For example, some companies may prefer a candidate who is highly independent and requires little to no interaction. The interviewer will scan through your resume and ask how you had worked in your previous companies and your preferred working method. You will have an understanding that they require an independent employee and can draw out past experiences where you were independent.

## List of important topics for the interview



