# Maintaining legal residency for International students {-}
## F-1 Students {-}
> Being an international student with an F-1 visa, this document will guide you to maintain a legal residency in the US while working off campus. Please keep in mind that any off-campus job for F-1 students must be allowed. Off-campus employment without the appropriate work permit would be viewed as a breach of your F-1 requirements. Losing one's legal immigration status in the United States, a potential deportation by the Department of Homeland Security, and extremely difficult future attempts to obtain a visa for entry into the United States would most likely be the results.

### CPT {-}

Curricular practical training(CPT) is working off campus during the program. Each semester, this work authorization is approved. This is for students who get an internship while enrolling full-time in the program.

  + Part-time VS Full-time

Part-time CPT: Work that is 20 hours a week or less is regarded as part-time. To preserve legal F-1 status for the fall and winter terms, you must be enrolled in classes full-time and physically present on campus at all times. 

Full-time CPT: A job is considered full-time if it requires more than 20 hours a week. Please be informed that after completing 12 consecutive months of full-time CPT, you will not be eligible for Optional Practical Training (OPT). You must enroll full-time or have a certified reduced course load for the fall and winter terms (RCL).

### OPT {-}

The Federal Regulations describe OPT as temporary work that is closely related to a student's field of study. A student maintains F-1 status throughout OPT. An Employment Authorization Document (EAD), issued by United States Citizenship and Immigration Services, is the result of the OPT request process (USCIS).

For the student to be qualified for OPT, they must: 
occupy a valid F-1 visa status. 
have studied full-time for at least one academic year. 
have U-M-approved health insurance

The typical OPT period has a 12-month maximum cumulative length. The 12-month cap is reduced by 50% for part-time OPT. Some F-1 students with degrees in science, technology, engineering, and mathematics (STEM) may request an extension of their optional practical training program by 24 months (OPT). If an F-1 moves up to a higher educational level, they might qualify for another 12 months of OPT.

### Useful resources for wolverines {-}
[UM Difference between Employment and Volunteering](https://internationalcenter.umich.edu/students/employment-volunteer)

[UM Applying for Curricular Practical Training(F-1 Students)](https://internationalcenter.umich.edu/students/f1-students/cpt)

[UM Applying for Optional Practical Training(F-1 Students)](https://internationalcenter.umich.edu/students/f1-students/apply-opt)

[UM OPT STEM Extension](https://internationalcenter.umich.edu/students/f1-students/stem-extend) 
