---
title: "MBAn Career Handbook Group Project Proposal"
author: "Team Keep Rolling"
date: '2022-07-17'
output: 
  html_document:
    theme:
      bootswatch: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MBAn Career Handbook

### Executive summary
> This handbook is for current and future MBAn students to understand how the program works, what the targeted jobs are, and how to prepare for recruiting processes. The handbook will first begin with an overview of the MBAn program, describing different resources available from the Ross experience, classes you may take, and the skills gained from it. Following this introduction, we will transition into the main section of the book, detailing career outcomes available to MBAn students, driven by research from other school’s Business Analytics program, the CDO resources, and experiences from former Master of Management students that have moved onto careers. We will introduce techniques for going through career exploration independently while utilizing the guide. Next will be a chapter focusing on the overall recruiting process for the discussed careers and how MBAn students can prepare and plan for networking, applications, and interviews. We will accumulate best practices for resumes, cover letters, and interviews. A final section will be included detailing supportive resources for the challenges international students face when searching for careers in the U.S. and globally, including a dynamic list of companies that offer sponsorship. We recognize research and resources our team is able to provide over the next few weeks is non-exhaustive, but we hope for this handbook to be a baseline for future students of this program and can live on and be updated in the future as the Master of Business Analytics Graduates enter the workforce and find success in their careers.

### Why do we choose MBAn at Ross?
* Expected values gained from investing your time and money
* Coursework
* Career resources
* Long-term gains

### Career choices
* Expected career outcomes after MBAn (Things to prepare for the specific roles) TBD
  + Consulting 
  + Product Management
  + Data Analyst (Business Analyst)
  + Be brave to reaching out and talking to people (alumni & other school’s business analytics), insights from alumni in analytical roles & CDO 
List of companies for these roles, including whether to offer sponsorship or not
* Decide your own dream direction and dream companies appropriate for you most(LAMP list）

### Recruiting process
* Resume preparation process 
 + What’s in your “Toolbox”
 + What resources does OYM provide?
 +List and links to useful resources to look out for

* Interview preparation process

 + Sample questions
 + Mock interviews
 + Interview Prep books (reaching out to full-time mba(consulting club) and mm (who has experience))
 + Expected timeline and plan
 + Schedule for different industries recruiting practices
 + Deadlines to give yourself to be prepared and proactive
 + Time management for balancing recruiting and classes simultaneously
			
### Challenges for International students.
* Sponsorship
* H1B process
* Resources
 
 
#### Pointers to work on  
 + Business Analytics is domain independent.
 + Keep track of references.
 + Use glassdoor as a reference.
 + Taking in first hand references from Alum.


